# 1. Choose OS (Ubuntu 14.04.3 LTS Server Edition 64bit, ~2 CORE, 7.5GB RAM)
sudo: required

# 2. Choose language and target JDKs for parallel builds.
language: java
jdk:
  - openjdk8

# 3. Setup cache directory for SBT and Maven.
cache:
  directories:
  - $HOME/.m2

# 4. Run maven install before running lint-java.
install:
  -

script:
  - set -e
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
  - export PING_SLEEP=5s
  - export WORKDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  - export BUILD_OUTPUT=$WORKDIR/build.out
  - touch $BUILD_OUTPUT
  - dump_output() {
  -   echo Tailing the last 500 lines of output:
  -   tail -500 $BUILD_OUTPUT  
  - }
  - error_handler() {
  -   echo ERROR: An error was encountered with the build.
  -   dump_output
  -   exit 1
  - }
  - trap 'error_handler' ERR
  - bash -c "while true; do echo \$(date) - building ...; sleep $PING_SLEEP; done" &
  - PING_LOOP_PID=$!
  - mvn clean package -DskipTests >> $BUILD_OUTPUT 2>&1
  - dump_output
  - kill $PING_LOOP_PID

# 5. Branches only
branches:
  only:
  - master
  - master-2.x
